require('dotenv').config()

const config = {
  DEMIRTECH_DATABASE_NAME: process.env.DEMIRTECH_DATABASE_NAME,
  DEMIRTECH_DATABASE_CONNECTION_URL: process.env.DEMIRTECH_DATABASE_CONNECTION_URL,
  DEMIRTECH_APPLICATION_PORT: process.env.DEMIRTECH_APPLICATION_PORT,
  DEMIRTECH_JWT_SECRET: process.env.JWT_SECRET,
  DEMIRTECH_JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
  DEMIRTECH_MAILTRAP_TOKEN: process.env.DEMIRTECH_MAILTRAP_TOKEN,
  DEMIRTECH_MAILTRAP_ENDPOINT: process.env.DEMIRTECH_MAILTRAP_ENDPOINT,
  DEMIRTECH_CLIENT_URL: process.env.DEMIRTECH_CLIENT_URL,
}

module.exports = config